# Generated by Django 5.1.6 on 2025-04-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_chat', '0003_aichatmessage'),
    ]

    operations = [
        # No operations needed - this is a no-op migration
    ]
